[package]
name = "wasm-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
wasm-parser = { path = "../wasm-parser" }
wasm-validator = { path = "../wasm-validator" }

[dev-dependencies]
wast = "=217.0.0"

[lints]
workspace = true
