from pathlib import Path

p=Path('crates/wasm-validator/src/typed.rs')
s=p.read_text()
old='''                    16 => {\n                        let table_index = read_u32(code, &mut pc, function, offset)?;\n                        if table_index != 0 || table_index as usize >= module.table_count() {\n                            return Err(ValidationError::TableIndexOutOfBounds {\n                                function,\n                                offset,\n                                table_index,\n                            });\n                        }\n                        stack.push(ValueType::I32);\n                    }\n                    _ => {'''
new='''                    16 => {\n                        let table_index = read_u32(code, &mut pc, function, offset)?;\n                        if table_index != 0 || table_index as usize >= module.table_count() {\n                            return Err(ValidationError::TableIndexOutOfBounds {\n                                function,\n                                offset,\n                                table_index,\n                            });\n                        }\n                        stack.push(ValueType::I32);\n                    }\n                    17 => {\n                        let table_index = read_u32(code, &mut pc, function, offset)?;\n                        if table_index != 0 || table_index as usize >= module.table_count() {\n                            return Err(ValidationError::TableIndexOutOfBounds {\n                                function,\n                                offset,\n                                table_index,\n                            });\n                        }\n                        pop_expect(&mut stack, &controls, ValueType::I32, function, offset)?;\n                        pop_expect(&mut stack, &controls, ValueType::FuncRef, function, offset)?;\n                        pop_expect(&mut stack, &controls, ValueType::I32, function, offset)?;\n                    }\n                    _ => {'''
assert old in s
p.write_text(s.replace(old,new))

p=Path('crates/wasm-runtime/src/lib.rs'); s=p.read_text()
old='''                        16 => {\n                            let table_index = read_u32_immediate(code, &mut pc)?;\n                            stack.push(Value::I32(self.table_size(table_index)?));\n                        }\n                        _ => {'''
new='''                        16 => {\n                            let table_index = read_u32_immediate(code, &mut pc)?;\n                            stack.push(Value::I32(self.table_size(table_index)?));\n                        }\n                        17 => {\n                            let table_index = read_u32_immediate(code, &mut pc)?;\n                            let length = numeric::i32_from_stack(&mut stack)?;\n                            let value = match stack.pop().ok_or(RuntimeError::StackUnderflow)? {\n                                Value::FuncRef(value) => value,\n                                other => return Err(RuntimeError::ValueTypeMismatch {\n                                    expected: ValueType::FuncRef,\n                                    actual: other.value_type(),\n                                }),\n                            };\n                            let destination = numeric::i32_from_stack(&mut stack)?;\n                            self.table_fill(table_index, destination, value, length)?;\n                        }\n                        _ => {'''
assert old in s; s=s.replace(old,new)
old='''    fn table_size(&self, table_index: u32) -> Result<i32, RuntimeError> {'''
new='''    fn table_fill(\n        &mut self,\n        table_index: u32,\n        destination: i32,\n        value: Option<u32>,\n        length: i32,\n    ) -> Result<(), RuntimeError> {\n        if table_index != 0 {\n            return Err(RuntimeError::TableElementOutOfBounds(table_index));\n        }\n        let width = length as u32 as usize;\n        let destination_start = u64::from(destination as u32);\n        let table = self\n            .table\n            .as_ref()\n            .ok_or(RuntimeError::TableElementOutOfBounds(destination as u32))?;\n        let destination_end = destination_start\n            .checked_add(width as u64)\n            .ok_or(RuntimeError::TableElementOutOfBounds(destination as u32))?;\n        if destination_end > u64::from(table.len()) {\n            return Err(RuntimeError::TableElementOutOfBounds(destination as u32));\n        }\n        let replacement = value.map(|function_index| FunctionRef {\n            owner: Rc::downgrade(&self.identity),\n            function_index,\n        });\n        let start = destination_start as usize;\n        let mut slots = table.slots.borrow_mut();\n        slots[start..start + width].fill(replacement);\n        Ok(())\n    }\n\n    fn table_size(&self, table_index: u32) -> Result<i32, RuntimeError> {'''
assert old in s; s=s.replace(old,new)
old='''                    16 => {\n                        let _ = read_u32_immediate(code, &mut pc)?;\n                    }\n                    _ => {'''
new='''                    16 | 17 => {\n                        let _ = read_u32_immediate(code, &mut pc)?;\n                    }\n                    _ => {'''
assert old in s
p.write_text(s.replace(old,new))
